// Collect narration/scene-XX.timing.json into scenes/lib/timings.js so scenes can load it
// with a plain <script> tag (file:// pages cannot fetch JSON).
// Usage (from video/): node narration/build-timings.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = path.dirname(fileURLToPath(import.meta.url));
const out = {};
for (const f of readdirSync(DIR).filter((f) => /^[a-z]+-\d\d\.timing\.json$/.test(f)).sort()) {
  // Captions show figures as numerals even where the voice script spells them out.
  out[f.replace('.timing.json', '')] = JSON.parse(readFileSync(path.join(DIR, f), 'utf8')).segments.map((s) => ({
    ...s,
    text: s.text
      .replace(/twenty thirty-five/g, '2035').replace(/twenty thirty/g, '2030')
      .replace(/twenty twenty-(one|four|five|six)/g, (_, d) => '202' + { one: 1, four: 4, five: 5, six: 6 }[d]),
  }));
}
const dest = path.join(DIR, '..', 'scenes', 'lib', 'timings.js');
writeFileSync(dest, `// Generated by narration/build-timings.mjs. Do not edit.\nwindow.TIMINGS = ${JSON.stringify(out, null, 1)};\n`);
console.log(`wrote ${Object.keys(out).length} scenes to ${path.relative(process.cwd(), dest)}`);
