// Generated by narration/build-timings.mjs. Do not edit.
window.TIMINGS = {
 "scene-01": [
  {
   "start": 0,
   "end": 3.35,
   "text": "At night, most of this hospital sleeps."
  },
  {
   "start": 4.35,
   "end": 9.35,
   "text": "One part never does — the part that waits."
  },
  {
   "start": 11.35,
   "end": 19.2,
   "text": "Here, in a quiet corner of Germany, a hospital is being asked to change its shape."
  },
  {
   "start": 20.2,
   "end": 24.1,
   "text": "It begins with a very small operation."
  }
 ],
 "scene-02": [
  {
   "start": 0,
   "end": 8.35,
   "text": "A groin hernia is a weak point in the wall of the body. Most patients need no night in hospital to repair it."
  },
  {
   "start": 9.35,
   "end": 18.35,
   "text": "In Scandinavia and Britain, most go home the same day. In Germany, most have stayed the night."
  },
  {
   "start": 19.35,
   "end": 29.6,
   "text": "Now the rules have changed. For a simple case, the hospital is paid one fixed price — whether the patient goes home that evening, or stays until morning."
  },
  {
   "start": 30.6,
   "end": 40.1,
   "text": "Who is fit to go home remains a doctor's decision. The price simply stops paying for nights that are not needed."
  }
 ],
 "scene-03": [
  {
   "start": 0,
   "end": 18.85,
   "text": "To the insurers, this change is overdue. Germany has more hospital beds per person than any country in the European Union but one. It spends more on health per person than any of them. Yet its people live no longer than the European average."
  },
  {
   "start": 19.85,
   "end": 24.95,
   "text": "Some shrinking, they argue, is not the illness."
  },
  {
   "start": 26.45,
   "end": 29.05,
   "text": "It is the cure."
  }
 ],
 "scene-04": [
  {
   "start": 0,
   "end": 13.95,
   "text": "The pressure runs deeper. One German in five is sixty-seven or over; by 2035, it will be one in four. Fewer workers pay in. More patients need care."
  },
  {
   "start": 14.95,
   "end": 26.65,
   "text": "And the economy that paid the bills is losing power — the cheap Russian gas is gone, and Chinese factories now compete with German ones."
  },
  {
   "start": 27.65,
   "end": 40.15,
   "text": "So the weight passes down. Government limits what it adds. Insurers fix their prices. The regions delay new buildings. Each decision is reasonable."
  },
  {
   "start": 41.15,
   "end": 49.45,
   "text": "And near the bottom sits a hospital that cannot pass on its night shift, its emergency team, or its walls."
  }
 ],
 "scene-05": [
  {
   "start": 0,
   "end": 18.95,
   "text": "When a patient goes home, a bed empties. On paper, a few hundred euros vanish from the bill. But the nurse is still on the rota. Little money is saved — until the hospital truly changes what it spends."
  },
  {
   "start": 19.95,
   "end": 28.6,
   "text": "And there is the part that cannot sleep. For years, routine operations helped to pay for it."
  },
  {
   "start": 29.6,
   "end": 39.4,
   "text": "Two German hospitals in three are losing money. A payment just for staying ready is now law — but it arrives in full only in 2030."
  },
  {
   "start": 40.9,
   "end": 43.85,
   "text": "The new price is already here."
  }
 ],
 "scene-06": [
  {
   "start": 0,
   "end": 7.4,
   "text": "Who pays for a new shape? In Germany, the state pays for buildings; the insurers pay for treatment."
  },
  {
   "start": 8.4,
   "end": 24.95,
   "text": "Here, the state has set aside eighty-five million euros for a new campus — with an outpatient theatre where hospital surgeons and local doctors will work side by side. Once the money is confirmed, it could open in five or six years."
  },
  {
   "start": 25.95,
   "end": 41,
   "text": "The hospitals that adapt well give day surgery its own space, decide before the day who goes home, and choose what to do with the empty bed: close it, or give it to someone who is waiting."
  }
 ],
 "scene-07": [
  {
   "start": 0,
   "end": 9.3,
   "text": "When our patient leaves, the care changes address. Someone must drive them home. Someone should be there tonight."
  },
  {
   "start": 10.3,
   "end": 18.55,
   "text": "For those who live alone, or far away, or are frail, the night in hospital was never a habit."
  },
  {
   "start": 20.55,
   "end": 23.1,
   "text": "It was the care."
  },
  {
   "start": 24.1,
   "end": 32.1,
   "text": "Work that leaves the ward does not vanish. It arrives in a kitchen, a spare room, a daughter's evening."
  }
 ],
 "scene-08": [
  {
   "start": 0,
   "end": 13.05,
   "text": "The rules around this hospital can change in a single year. Its body changes slowly — the rotas, the wards, the lights that stay on for an emergency that has not yet arrived."
  },
  {
   "start": 14.05,
   "end": 22.45,
   "text": "No one in the chain chose this. Each simply passed on what it could not carry."
  },
  {
   "start": 23.45,
   "end": 31.25,
   "text": "Whether this becomes a hospital that adapts, or one that merely shrinks, will not be told by the empty bed."
  },
  {
   "start": 33.25,
   "end": 42.2,
   "text": "It will be told by the patient who recovers well at home — and by whether someone is still here, awake, when they need to come back."
  }
 ]
};
