// Generated by narration/build-timings.mjs. Do not edit.
window.TIMINGS = {
 "ptb-01": [
  {
   "start": 0,
   "end": 20.8,
   "text": "Germany's hospitals say they're underfunded. The insurers say hospitals cost too much. Surgeons say the prices ignore what surgery really takes. The states say Berlin is meddling. Berlin says the system has too many beds and too little reform."
  },
  {
   "start": 21.8,
   "end": 26.45,
   "text": "Everyone feels the pressure. Everyone points somewhere else."
  },
  {
   "start": 27.95,
   "end": 37.25,
   "text": "To find out who's right, we'll follow one small operation through the whole machine — and see where the blame finally lands."
  }
 ],
 "ptb-02": [
  {
   "start": 0,
   "end": 3.1,
   "text": "Start with what nobody chose."
  },
  {
   "start": 4.1,
   "end": 18.7,
   "text": "One German in five is sixty-seven or over; by 2035, one in four. More patients, fewer people paying in. Health already costs more than five hundred billion euros a year."
  },
  {
   "start": 19.7,
   "end": 42.4,
   "text": "Contributions for health, pensions, care and unemployment take about forty-two percent of a typical salary. This year the public insurers' spending grew seven percent; their income, four. Without action, the government projected a gap of tens of billions a year by 2030 — and in July it passed a law to close it."
  },
  {
   "start": 43.4,
   "end": 60.7,
   "text": "And the economy that pays the bills has stalled: three years of almost no growth, energy-hungry industry down nearly a fifth since 2021, Chinese factories competing with German ones. Growth is expected to pick up a little, then fade again."
  },
  {
   "start": 61.7,
   "end": 69.85,
   "text": "Not a collapse. But money will be tight for a long time — and when money is tight, people look for someone to blame."
  }
 ],
 "ptb-03": [
  {
   "start": 0,
   "end": 6.95,
   "text": "Our operation: a groin hernia repair. Germany does about a quarter of a million a year."
  },
  {
   "start": 7.95,
   "end": 29.25,
   "text": "In England and Sweden, about four in five patients go home the same day. In Germany, closer to one in seven — partly because the old payment rules made the overnight stay the default. For most patients that night isn't needed; studies of carefully selected patients find no difference in complications."
  },
  {
   "start": 30.25,
   "end": 45.15,
   "text": "So from 2024 Germany set one price for this operation and many others — the same whether the patient goes home or stays the night. For a simple repair this year: about two thousand euros."
  },
  {
   "start": 46.15,
   "end": 51.25,
   "text": "A sensible fix. So why is everyone at the table unhappy?"
  }
 ],
 "ptb-04": [
  {
   "start": 0,
   "end": 14.15,
   "text": "The insurers point at the bill. Their own research institute found that across these same-price operations, spending in 2025 was about three hundred and sixty million euros higher, after inflation."
  },
  {
   "start": 15.15,
   "end": 28.7,
   "text": "The price blended the old hospital rate with the old outpatient rate — so operations once done cheaply in doctors' practices now earned more. And cases rose by seventeen percent."
  },
  {
   "start": 29.7,
   "end": 47.2,
   "text": "So is it the hospitals' and doctors' fault? Not quite. Insurers don't set these prices alone: they negotiate them with hospitals and doctors. This year the three sides couldn't agree, and an arbitration committee decided."
  },
  {
   "start": 48.2,
   "end": 50.5,
   "text": "The beam moves on."
  }
 ],
 "ptb-05": [
  {
   "start": 0,
   "end": 19.25,
   "text": "The hospitals point at what's left behind. One price suits the simplest patients, and they're the easiest to treat elsewhere — industry voices say some outpatient centres pick exactly those. The frail, the repeats, the large hernias and the emergencies still come up the hill."
  },
  {
   "start": 20.25,
   "end": 33.35,
   "text": "And the hospital must stay ready all night. A readiness payment is coming by 2030 — but it's mostly existing money moved into a fixed budget, not new money."
  },
  {
   "start": 34.35,
   "end": 56.8,
   "text": "Then there are the buildings. Those are meant to be paid by the states. The hospitals' association says the states cover only about half of what's needed. Two in three hospitals surveyed lost money in 2024. In Saarbrücken, the city is setting aside fifteen million euros this year to keep its hospital steady."
  },
  {
   "start": 57.8,
   "end": 68.5,
   "text": "Hospitals didn't write these rules. But they're not powerless either — they still choose which patients go home, how their theatres run, who they work with."
  },
  {
   "start": 69.5,
   "end": 72,
   "text": "The beam moves on."
  }
 ],
 "ptb-06": [
  {
   "start": 0,
   "end": 25,
   "text": "The surgeons point at what the price can't see. Most agree many patients could go home the same day. But the recommended repair — keyhole surgery with a mesh, with less pain afterwards — costs more on the day. In Germany, three quarters of inpatient repairs used it; only a third of outpatient ones. In Denmark, keyhole and same-day go together."
  },
  {
   "start": 26,
   "end": 43.95,
   "text": "And the next surgeon has to learn. Supervised residents in one study took ninety-four minutes; experienced surgeons, seventy — safely. The price has no line for those twenty-four minutes. The surgeons' society warned of exactly this."
  },
  {
   "start": 44.95,
   "end": 47.25,
   "text": "So — is it the government's fault?"
  }
 ],
 "ptb-07": [
  {
   "start": 0,
   "end": 18,
   "text": "Follow the decisions upward. Berlin writes the rules: the single price, the readiness payment, a fund of up to fifty billion euros to help hospitals restructure. It argues there are too many beds and too much care done too rarely to be done well."
  },
  {
   "start": 19,
   "end": 30.35,
   "text": "The states plan the hospitals and are meant to pay for the buildings. Several pushed back on Berlin's reform as an intrusion into their planning."
  },
  {
   "start": 31.35,
   "end": 44.1,
   "text": "Berlin points to the states. The states point to Berlin. Both point to the negotiators. The negotiators point to the law."
  },
  {
   "start": 45.3,
   "end": 67.55,
   "text": "Step back and you see why. The money for buildings and the money for treatment come through different pipes. Rules come from one capital, planning from another, prices from a table where no side can decide alone. No one owns a patient's whole journey — from the doctor's practice, to the operating theatre, to the bed at home."
  },
  {
   "start": 68.75,
   "end": 74.05,
   "text": "In a machine like this, blame never has to land anywhere."
  }
 ],
 "ptb-08": [
  {
   "start": 0,
   "end": 3.05,
   "text": "So, who is to blame?"
  },
  {
   "start": 4.05,
   "end": 16.4,
   "text": "Some of it is no one's fault. An older country and a slower economy squeeze everyone — insurers, hospitals, surgeons, governments — at the same time."
  },
  {
   "start": 17.4,
   "end": 33.2,
   "text": "Some of it is the design. When responsibility is split between two capitals, two pipes and a negotiating table, every problem can be passed along, and every actor can be right about someone else."
  },
  {
   "start": 34.2,
   "end": 59.15,
   "text": "And some of it is choices — which means it can change. A price that pays nothing for training or for the hardest cases. A readiness payment that moves money rather than adding it. Buildings the states pay for only in part. Rules that for years made the night in hospital the default."
  },
  {
   "start": 60.35,
   "end": 83,
   "text": "The direction — sending more patients safely home — is right. The pressure is real. But blame is the easy part. The harder question is ownership: who will be responsible for the whole journey, and be judged by what happens to the patient in that home?"
  },
  {
   "start": 84.2,
   "end": 88.8,
   "text": "Until someone owns that, everyone will keep pointing."
  }
 ],
 "scene-01": [
  {
   "start": 0,
   "end": 3.35,
   "text": "At night, most of this hospital sleeps."
  },
  {
   "start": 4.35,
   "end": 9.35,
   "text": "One part never does — the part that waits."
  },
  {
   "start": 11.35,
   "end": 19.2,
   "text": "Here, in a quiet corner of Germany, a hospital is being asked to change its shape."
  },
  {
   "start": 20.2,
   "end": 24.1,
   "text": "It begins with a very small operation."
  }
 ],
 "scene-02": [
  {
   "start": 0,
   "end": 8.35,
   "text": "A groin hernia is a weak point in the wall of the body. Most patients need no night in hospital to repair it."
  },
  {
   "start": 9.35,
   "end": 18.35,
   "text": "In Scandinavia and Britain, most go home the same day. In Germany, most have stayed the night."
  },
  {
   "start": 19.35,
   "end": 29.6,
   "text": "Now the rules have changed. For a simple case, the hospital is paid one fixed price — whether the patient goes home that evening, or stays until morning."
  },
  {
   "start": 30.6,
   "end": 40.1,
   "text": "Who is fit to go home remains a doctor's decision. The price simply stops paying for nights that are not needed."
  }
 ],
 "scene-03": [
  {
   "start": 0,
   "end": 18.85,
   "text": "To the insurers, this change is overdue. Germany has more hospital beds per person than any country in the European Union but one. It spends more on health per person than any of them. Yet its people live no longer than the European average."
  },
  {
   "start": 19.85,
   "end": 24.95,
   "text": "Some shrinking, they argue, is not the illness."
  },
  {
   "start": 26.45,
   "end": 29.05,
   "text": "It is the cure."
  }
 ],
 "scene-04": [
  {
   "start": 0,
   "end": 13.95,
   "text": "The pressure runs deeper. One German in five is sixty-seven or over; by 2035, it will be one in four. Fewer workers pay in. More patients need care."
  },
  {
   "start": 14.95,
   "end": 26.65,
   "text": "And the economy that paid the bills is losing power — the cheap Russian gas is gone, and Chinese factories now compete with German ones."
  },
  {
   "start": 27.65,
   "end": 40.15,
   "text": "So the weight passes down. Government limits what it adds. Insurers fix their prices. The regions delay new buildings. Each decision is reasonable."
  },
  {
   "start": 41.15,
   "end": 49.45,
   "text": "And near the bottom sits a hospital that cannot pass on its night shift, its emergency team, or its walls."
  }
 ],
 "scene-05": [
  {
   "start": 0,
   "end": 18.95,
   "text": "When a patient goes home, a bed empties. On paper, a few hundred euros vanish from the bill. But the nurse is still on the rota. Little money is saved — until the hospital truly changes what it spends."
  },
  {
   "start": 19.95,
   "end": 28.6,
   "text": "And there is the part that cannot sleep. For years, routine operations helped to pay for it."
  },
  {
   "start": 29.6,
   "end": 39.4,
   "text": "Two German hospitals in three are losing money. A payment just for staying ready is now law — but it arrives in full only in 2030."
  },
  {
   "start": 40.9,
   "end": 43.85,
   "text": "The new price is already here."
  }
 ],
 "scene-06": [
  {
   "start": 0,
   "end": 7.4,
   "text": "Who pays for a new shape? In Germany, the state pays for buildings; the insurers pay for treatment."
  },
  {
   "start": 8.4,
   "end": 24.95,
   "text": "Here, the state has set aside eighty-five million euros for a new campus — with an outpatient theatre where hospital surgeons and local doctors will work side by side. Once the money is confirmed, it could open in five or six years."
  },
  {
   "start": 25.95,
   "end": 41,
   "text": "The hospitals that adapt well give day surgery its own space, decide before the day who goes home, and choose what to do with the empty bed: close it, or give it to someone who is waiting."
  }
 ],
 "scene-07": [
  {
   "start": 0,
   "end": 9.3,
   "text": "When our patient leaves, the care changes address. Someone must drive them home. Someone should be there tonight."
  },
  {
   "start": 10.3,
   "end": 18.55,
   "text": "For those who live alone, or far away, or are frail, the night in hospital was never a habit."
  },
  {
   "start": 20.55,
   "end": 23.1,
   "text": "It was the care."
  },
  {
   "start": 24.1,
   "end": 32.1,
   "text": "Work that leaves the ward does not vanish. It arrives in a kitchen, a spare room, a daughter's evening."
  }
 ],
 "scene-08": [
  {
   "start": 0,
   "end": 13.05,
   "text": "The rules around this hospital can change in a single year. Its body changes slowly — the rotas, the wards, the lights that stay on for an emergency that has not yet arrived."
  },
  {
   "start": 14.05,
   "end": 22.45,
   "text": "No one in the chain chose this. Each simply passed on what it could not carry."
  },
  {
   "start": 23.45,
   "end": 31.25,
   "text": "Whether this becomes a hospital that adapts, or one that merely shrinks, will not be told by the empty bed."
  },
  {
   "start": 33.25,
   "end": 42.2,
   "text": "It will be told by the patient who recovers well at home — and by whether someone is still here, awake, when they need to come back."
  }
 ]
};
